import { eq, and, desc, asc } from "drizzle-orm";
import { database } from "~/db";
import {
  familyMemberEvent,
  type FamilyMemberEvent,
  type CreateFamilyMemberEventData,
  type UpdateFamilyMemberEventData,
} from "~/db/schema";

// Find a family member event by ID
export async function findFamilyMemberEventById(
  id: string
): Promise<FamilyMemberEvent | null> {
  const [result] = await database
    .select()
    .from(familyMemberEvent)
    .where(eq(familyMemberEvent.id, id))
    .limit(1);

  return result || null;
}

// Find all events for a family member, sorted by date
export async function findEventsByFamilyMemberId(
  familyMemberId: string
): Promise<FamilyMemberEvent[]> {
  return database
    .select()
    .from(familyMemberEvent)
    .where(eq(familyMemberEvent.familyMemberId, familyMemberId))
    .orderBy(asc(familyMemberEvent.eventDate), asc(familyMemberEvent.eventYear));
}

// Find all events for a family tree
export async function findEventsByFamilyTreeId(
  familyTreeId: string
): Promise<FamilyMemberEvent[]> {
  return database
    .select()
    .from(familyMemberEvent)
    .where(eq(familyMemberEvent.familyTreeId, familyTreeId))
    .orderBy(asc(familyMemberEvent.eventDate), asc(familyMemberEvent.eventYear));
}

// Create a new family member event
export async function createFamilyMemberEvent(
  data: CreateFamilyMemberEventData
): Promise<FamilyMemberEvent> {
  const [result] = await database
    .insert(familyMemberEvent)
    .values(data)
    .returning();

  return result;
}

// Create multiple family member events
export async function createFamilyMemberEvents(
  data: CreateFamilyMemberEventData[]
): Promise<FamilyMemberEvent[]> {
  if (data.length === 0) return [];
  return database.insert(familyMemberEvent).values(data).returning();
}

// Update a family member event
export async function updateFamilyMemberEvent(
  id: string,
  data: UpdateFamilyMemberEventData
): Promise<FamilyMemberEvent | null> {
  const [result] = await database
    .update(familyMemberEvent)
    .set({ ...data, updatedAt: new Date() })
    .where(eq(familyMemberEvent.id, id))
    .returning();

  return result || null;
}

// Delete a family member event
export async function deleteFamilyMemberEvent(id: string): Promise<boolean> {
  const result = await database
    .delete(familyMemberEvent)
    .where(eq(familyMemberEvent.id, id))
    .returning({ id: familyMemberEvent.id });

  return result.length > 0;
}

// Delete all events for a family member
export async function deleteEventsByFamilyMemberId(
  familyMemberId: string
): Promise<number> {
  const result = await database
    .delete(familyMemberEvent)
    .where(eq(familyMemberEvent.familyMemberId, familyMemberId))
    .returning({ id: familyMemberEvent.id });

  return result.length;
}

// Delete all auto-generated events for a family member (useful when updating from existing data)
export async function deleteAutoGeneratedEventsByMemberId(
  familyMemberId: string
): Promise<number> {
  const result = await database
    .delete(familyMemberEvent)
    .where(
      and(
        eq(familyMemberEvent.familyMemberId, familyMemberId),
        eq(familyMemberEvent.isAutoGenerated, true)
      )
    )
    .returning({ id: familyMemberEvent.id });

  return result.length;
}
