"use client";

import { useState } from "react";
import {
  Baby,
  Heart,
  HeartCrack,
  GraduationCap,
  Briefcase,
  Trophy,
  Home,
  Stethoscope,
  Medal,
  Church,
  Star,
  Plus,
  Pencil,
  Trash2,
  Calendar,
  MapPin,
  Loader2,
} from "lucide-react";
import { Button } from "~/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { Badge } from "~/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "~/components/ui/dialog";
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "~/components/ui/alert-dialog";
import { TimelineEventForm, EVENT_TYPE_LABELS, type TimelineEventFormData } from "./TimelineEventForm";
import {
  useFamilyMemberEvents,
  useCreateFamilyMemberEvent,
  useUpdateFamilyMemberEvent,
  useDeleteFamilyMemberEvent,
} from "~/hooks/useFamilyMemberEvents";
import type { FamilyMemberEvent, FamilyMemberEventType } from "~/db/schema";
import { cn } from "~/lib/utils";

// Icon mapping for event types
const EVENT_TYPE_ICONS: Record<FamilyMemberEventType, React.ElementType> = {
  birth: Baby,
  death: Heart,
  marriage: Heart,
  divorce: HeartCrack,
  child_born: Baby,
  graduation: GraduationCap,
  career: Briefcase,
  achievement: Trophy,
  residence: Home,
  medical: Stethoscope,
  military: Medal,
  religious: Church,
  other: Star,
};

// Color mapping for event types
const EVENT_TYPE_COLORS: Record<FamilyMemberEventType, string> = {
  birth: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
  death: "bg-gray-100 text-gray-700 dark:bg-gray-900/30 dark:text-gray-400",
  marriage: "bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-400",
  divorce: "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400",
  child_born: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
  graduation: "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
  career: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400",
  achievement: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400",
  residence: "bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-400",
  medical: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
  military: "bg-slate-100 text-slate-700 dark:bg-slate-900/30 dark:text-slate-400",
  religious: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
  other: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-400",
};

interface TimelineEventCardProps {
  event: FamilyMemberEvent;
  onEdit: (event: FamilyMemberEvent) => void;
  onDelete: (event: FamilyMemberEvent) => void;
  isOwner: boolean;
}

function TimelineEventCard({ event, onEdit, onDelete, isOwner }: TimelineEventCardProps) {
  const Icon = EVENT_TYPE_ICONS[event.eventType] || Star;
  const colorClass = EVENT_TYPE_COLORS[event.eventType] || EVENT_TYPE_COLORS.other;

  const formatDate = (dateStr: string | null, year: number | null) => {
    if (dateStr) {
      return new Date(dateStr).toLocaleDateString("en-US", {
        year: "numeric",
        month: "long",
        day: "numeric",
      });
    }
    if (year) {
      return year.toString();
    }
    return "Date unknown";
  };

  return (
    <div className="relative flex gap-4 pb-8 last:pb-0" data-testid="timeline-event-card">
      {/* Timeline line */}
      <div className="absolute left-5 top-10 bottom-0 w-0.5 bg-border last:hidden" />

      {/* Icon */}
      <div
        className={cn(
          "relative z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full",
          colorClass
        )}
      >
        <Icon className="h-5 w-5" />
      </div>

      {/* Content */}
      <div className="flex-1 pt-0.5">
        <div className="flex items-start justify-between gap-2">
          <div className="flex-1">
            <div className="flex items-center gap-2 flex-wrap">
              <h4 className="font-semibold text-foreground" data-testid="event-title">
                {event.title}
              </h4>
              <Badge variant="secondary" className="text-xs">
                {EVENT_TYPE_LABELS[event.eventType]}
              </Badge>
              {event.isAutoGenerated && (
                <Badge variant="outline" className="text-xs">
                  Auto
                </Badge>
              )}
            </div>

            <div className="flex items-center gap-3 mt-1 text-sm text-muted-foreground">
              <span className="flex items-center gap-1">
                <Calendar className="h-3.5 w-3.5" />
                {formatDate(event.eventDate, event.eventYear)}
              </span>
              {event.location && (
                <span className="flex items-center gap-1">
                  <MapPin className="h-3.5 w-3.5" />
                  {event.location}
                </span>
              )}
            </div>

            {event.description && (
              <p className="mt-2 text-sm text-muted-foreground">
                {event.description}
              </p>
            )}
          </div>

          {isOwner && !event.isAutoGenerated && (
            <div className="flex items-center gap-1">
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8"
                onClick={() => onEdit(event)}
                data-testid="edit-event-button"
              >
                <Pencil className="h-4 w-4" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="h-8 w-8 text-destructive hover:text-destructive"
                onClick={() => onDelete(event)}
                data-testid="delete-event-button"
              >
                <Trash2 className="h-4 w-4" />
              </Button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

interface MemberTimelineProps {
  familyMemberId: string;
  familyTreeId: string;
  memberName: string;
  isOwner: boolean;
}

export function MemberTimeline({
  familyMemberId,
  familyTreeId,
  memberName,
  isOwner,
}: MemberTimelineProps) {
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [editingEvent, setEditingEvent] = useState<FamilyMemberEvent | null>(null);
  const [deletingEvent, setDeletingEvent] = useState<FamilyMemberEvent | null>(null);

  const { data: events, isLoading, error } = useFamilyMemberEvents(familyMemberId);
  const createEvent = useCreateFamilyMemberEvent(familyMemberId, familyTreeId);
  const updateEvent = useUpdateFamilyMemberEvent(familyMemberId, familyTreeId);
  const deleteEvent = useDeleteFamilyMemberEvent(familyMemberId, familyTreeId);

  const handleCreateEvent = async (data: TimelineEventFormData) => {
    const parsedYear = data.eventYear ? parseInt(data.eventYear, 10) : null;
    await createEvent.mutateAsync({
      familyMemberId,
      eventType: data.eventType,
      title: data.title,
      description: data.description || null,
      eventDate: data.eventDate || null,
      eventYear: parsedYear && !isNaN(parsedYear) ? parsedYear : null,
      location: data.location || null,
    });
    setIsAddDialogOpen(false);
  };

  const handleUpdateEvent = async (data: TimelineEventFormData) => {
    if (!editingEvent) return;
    const parsedYear = data.eventYear ? parseInt(data.eventYear, 10) : null;
    await updateEvent.mutateAsync({
      id: editingEvent.id,
      eventType: data.eventType,
      title: data.title,
      description: data.description || null,
      eventDate: data.eventDate || null,
      eventYear: parsedYear && !isNaN(parsedYear) ? parsedYear : null,
      location: data.location || null,
    });
    setEditingEvent(null);
  };

  const handleDeleteEvent = async () => {
    if (!deletingEvent) return;
    await deleteEvent.mutateAsync(deletingEvent.id);
    setDeletingEvent(null);
  };

  // Sort events by date (earliest first)
  const sortedEvents = events
    ? [...events].sort((a, b) => {
        const dateA = a.eventDate
          ? new Date(a.eventDate).getTime()
          : a.eventYear
          ? new Date(a.eventYear, 0).getTime()
          : 0;
        const dateB = b.eventDate
          ? new Date(b.eventDate).getTime()
          : b.eventYear
          ? new Date(b.eventYear, 0).getTime()
          : 0;
        return dateA - dateB;
      })
    : [];

  if (isLoading) {
    return (
      <Card data-testid="member-timeline">
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <Calendar className="h-5 w-5" />
            Life Timeline
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="flex items-center justify-center py-8">
            <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
          </div>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card data-testid="member-timeline">
        <CardHeader>
          <CardTitle className="text-lg flex items-center gap-2">
            <Calendar className="h-5 w-5" />
            Life Timeline
          </CardTitle>
        </CardHeader>
        <CardContent>
          <p className="text-sm text-destructive">
            Failed to load timeline events. Please try again later.
          </p>
        </CardContent>
      </Card>
    );
  }

  return (
    <>
      <Card data-testid="member-timeline">
        <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4">
          <CardTitle className="text-lg flex items-center gap-2">
            <Calendar className="h-5 w-5" />
            Life Timeline
          </CardTitle>
          {isOwner && (
            <Button
              size="sm"
              onClick={() => setIsAddDialogOpen(true)}
              data-testid="add-event-button"
            >
              <Plus className="h-4 w-4 mr-1" />
              Add Event
            </Button>
          )}
        </CardHeader>
        <CardContent>
          {sortedEvents.length === 0 ? (
            <div className="text-center py-8" data-testid="empty-timeline">
              <Calendar className="h-12 w-12 mx-auto text-muted-foreground/50 mb-3" />
              <p className="text-sm text-muted-foreground">
                No timeline events yet.
              </p>
              {isOwner && (
                <p className="text-sm text-muted-foreground mt-1">
                  Add important life events like birth, marriage, career milestones, and more.
                </p>
              )}
            </div>
          ) : (
            <div className="space-y-0">
              {sortedEvents.map((event) => (
                <TimelineEventCard
                  key={event.id}
                  event={event}
                  onEdit={setEditingEvent}
                  onDelete={setDeletingEvent}
                  isOwner={isOwner}
                />
              ))}
            </div>
          )}
        </CardContent>
      </Card>

      {/* Add Event Dialog */}
      <Dialog open={isAddDialogOpen} onOpenChange={setIsAddDialogOpen}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Add Timeline Event</DialogTitle>
            <DialogDescription>
              Add an important event to {memberName}'s life timeline.
            </DialogDescription>
          </DialogHeader>
          <TimelineEventForm
            onSubmit={handleCreateEvent}
            isPending={createEvent.isPending}
            submitLabel="Add Event"
            onCancel={() => setIsAddDialogOpen(false)}
          />
        </DialogContent>
      </Dialog>

      {/* Edit Event Dialog */}
      <Dialog open={!!editingEvent} onOpenChange={(open) => !open && setEditingEvent(null)}>
        <DialogContent className="max-w-lg max-h-[90vh] overflow-y-auto">
          <DialogHeader>
            <DialogTitle>Edit Timeline Event</DialogTitle>
            <DialogDescription>
              Update the details of this timeline event.
            </DialogDescription>
          </DialogHeader>
          {editingEvent && (
            <TimelineEventForm
              defaultValues={{
                eventType: editingEvent.eventType,
                title: editingEvent.title,
                description: editingEvent.description || "",
                eventDate: editingEvent.eventDate || "",
                eventYear: editingEvent.eventYear ? editingEvent.eventYear.toString() : "",
                location: editingEvent.location || "",
              }}
              onSubmit={handleUpdateEvent}
              isPending={updateEvent.isPending}
              submitLabel="Update Event"
              onCancel={() => setEditingEvent(null)}
            />
          )}
        </DialogContent>
      </Dialog>

      {/* Delete Confirmation Dialog */}
      <AlertDialog open={!!deletingEvent} onOpenChange={(open) => !open && setDeletingEvent(null)}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>Delete Event</AlertDialogTitle>
            <AlertDialogDescription>
              Are you sure you want to delete "{deletingEvent?.title}"? This action cannot be undone.
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>Cancel</AlertDialogCancel>
            <AlertDialogAction
              onClick={handleDeleteEvent}
              className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
              disabled={deleteEvent.isPending}
            >
              {deleteEvent.isPending ? (
                <>
                  <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                  Deleting...
                </>
              ) : (
                "Delete"
              )}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </>
  );
}
