import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { authenticatedMiddleware } from "./middleware";
import {
  createFamilyMemberEvent,
  findFamilyMemberEventById,
  findEventsByFamilyMemberId,
  updateFamilyMemberEvent,
  deleteFamilyMemberEvent,
} from "~/data-access/family-member-events";
import { findFamilyMemberById } from "~/data-access/family-members";
import {
  findFamilyTreeById,
  isUserFamilyTreeOwner,
} from "~/data-access/family-trees";
import type { FamilyMemberEventType } from "~/db/schema";

// Event type enum for validation
const eventTypeSchema = z.enum([
  "birth",
  "death",
  "marriage",
  "divorce",
  "child_born",
  "graduation",
  "career",
  "achievement",
  "residence",
  "medical",
  "military",
  "religious",
  "other",
]);

const createFamilyMemberEventSchema = z.object({
  familyMemberId: z.string().min(1, "Family member ID is required"),
  eventType: eventTypeSchema,
  title: z
    .string()
    .min(1, "Title is required")
    .max(200, "Title must be less than 200 characters"),
  description: z
    .string()
    .max(2000, "Description must be less than 2000 characters")
    .nullable()
    .optional(),
  eventDate: z.string().nullable().optional(),
  eventYear: z.number().int().min(0).max(9999).nullable().optional(),
  location: z
    .string()
    .max(200, "Location must be less than 200 characters")
    .nullable()
    .optional(),
  relatedMemberId: z.string().nullable().optional(),
});

const updateFamilyMemberEventSchema = z.object({
  id: z.string().min(1, "Event ID is required"),
  eventType: eventTypeSchema.optional(),
  title: z
    .string()
    .min(1, "Title is required")
    .max(200, "Title must be less than 200 characters")
    .optional(),
  description: z
    .string()
    .max(2000, "Description must be less than 2000 characters")
    .nullable()
    .optional(),
  eventDate: z.string().nullable().optional(),
  eventYear: z.number().int().min(0).max(9999).nullable().optional(),
  location: z
    .string()
    .max(200, "Location must be less than 200 characters")
    .nullable()
    .optional(),
  relatedMemberId: z.string().nullable().optional(),
});

/**
 * Create a new family member event
 * Requires authentication and ownership of the family tree
 */
export const createFamilyMemberEventFn = createServerFn({
  method: "POST",
})
  .inputValidator(createFamilyMemberEventSchema)
  .middleware([authenticatedMiddleware])
  .handler(async ({ data, context }) => {
    // Verify the family member exists
    const familyMember = await findFamilyMemberById(data.familyMemberId);
    if (!familyMember) {
      throw new Error("Family member not found");
    }

    // Verify the user owns the family tree
    const isOwner = await isUserFamilyTreeOwner(
      context.userId,
      familyMember.familyTreeId
    );
    if (!isOwner) {
      throw new Error(
        "Unauthorized: You don't have permission to add events to this family member"
      );
    }

    // Create the event
    const eventData = {
      id: crypto.randomUUID(),
      familyTreeId: familyMember.familyTreeId,
      familyMemberId: data.familyMemberId,
      eventType: data.eventType as FamilyMemberEventType,
      title: data.title,
      description: data.description || null,
      eventDate: data.eventDate || null,
      eventYear: data.eventYear || null,
      location: data.location || null,
      relatedMemberId: data.relatedMemberId || null,
      isAutoGenerated: false,
    };

    const newEvent = await createFamilyMemberEvent(eventData);
    return newEvent;
  });

/**
 * Get a single family member event by ID
 * Requires authentication and access to the family tree
 */
export const getFamilyMemberEventByIdFn = createServerFn({
  method: "GET",
})
  .inputValidator(z.object({ id: z.string().min(1, "ID is required") }))
  .middleware([authenticatedMiddleware])
  .handler(async ({ data, context }) => {
    const event = await findFamilyMemberEventById(data.id);
    if (!event) {
      throw new Error("Event not found");
    }

    // Verify access to the family tree
    const familyTree = await findFamilyTreeById(event.familyTreeId);
    if (!familyTree) {
      throw new Error("Family tree not found");
    }

    const isOwner = familyTree.ownerId === context.userId;
    const isPublic = familyTree.isPublic;

    if (!isOwner && !isPublic) {
      throw new Error(
        "Unauthorized: You don't have permission to view this event"
      );
    }

    return event;
  });

/**
 * Get all events for a family member
 * Requires authentication and access to the family tree
 */
export const getEventsByFamilyMemberIdFn = createServerFn({
  method: "GET",
})
  .inputValidator(
    z.object({
      familyMemberId: z.string().min(1, "Family member ID is required"),
    })
  )
  .middleware([authenticatedMiddleware])
  .handler(async ({ data, context }) => {
    // Verify the family member exists
    const familyMember = await findFamilyMemberById(data.familyMemberId);
    if (!familyMember) {
      throw new Error("Family member not found");
    }

    // Verify access to the family tree
    const familyTree = await findFamilyTreeById(familyMember.familyTreeId);
    if (!familyTree) {
      throw new Error("Family tree not found");
    }

    const isOwner = familyTree.ownerId === context.userId;
    const isPublic = familyTree.isPublic;

    if (!isOwner && !isPublic) {
      throw new Error(
        "Unauthorized: You don't have permission to view events for this family member"
      );
    }

    const events = await findEventsByFamilyMemberId(data.familyMemberId);
    return events;
  });

/**
 * Update a family member event
 * Requires authentication and ownership of the family tree
 */
export const updateFamilyMemberEventFn = createServerFn({
  method: "POST",
})
  .inputValidator(updateFamilyMemberEventSchema)
  .middleware([authenticatedMiddleware])
  .handler(async ({ data, context }) => {
    const { id, ...updateData } = data;

    // Verify the event exists
    const existingEvent = await findFamilyMemberEventById(id);
    if (!existingEvent) {
      throw new Error("Event not found");
    }

    // Verify the user owns the family tree
    const isOwner = await isUserFamilyTreeOwner(
      context.userId,
      existingEvent.familyTreeId
    );
    if (!isOwner) {
      throw new Error(
        "Unauthorized: You don't have permission to update this event"
      );
    }

    // Don't allow editing auto-generated events
    if (existingEvent.isAutoGenerated) {
      throw new Error(
        "Cannot edit auto-generated events. Please update the related data instead."
      );
    }

    // Update the event
    const updatedEvent = await updateFamilyMemberEvent(id, {
      eventType: updateData.eventType as FamilyMemberEventType | undefined,
      title: updateData.title,
      description: updateData.description,
      eventDate: updateData.eventDate,
      eventYear: updateData.eventYear,
      location: updateData.location,
      relatedMemberId: updateData.relatedMemberId,
    });

    if (!updatedEvent) {
      throw new Error("Failed to update event");
    }

    return updatedEvent;
  });

/**
 * Delete a family member event
 * Requires authentication and ownership of the family tree
 */
export const deleteFamilyMemberEventFn = createServerFn({
  method: "POST",
})
  .inputValidator(z.object({ id: z.string().min(1, "ID is required") }))
  .middleware([authenticatedMiddleware])
  .handler(async ({ data, context }) => {
    const { id } = data;

    // Verify the event exists
    const existingEvent = await findFamilyMemberEventById(id);
    if (!existingEvent) {
      throw new Error("Event not found");
    }

    // Verify the user owns the family tree
    const isOwner = await isUserFamilyTreeOwner(
      context.userId,
      existingEvent.familyTreeId
    );
    if (!isOwner) {
      throw new Error(
        "Unauthorized: You don't have permission to delete this event"
      );
    }

    // Don't allow deleting auto-generated events
    if (existingEvent.isAutoGenerated) {
      throw new Error(
        "Cannot delete auto-generated events. Please update the related data instead."
      );
    }

    // Delete the event
    const deleted = await deleteFamilyMemberEvent(id);
    if (!deleted) {
      throw new Error("Failed to delete event");
    }

    return { success: true };
  });
