/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as TreeTreeIdRouteImport } from './routes/tree/$treeId'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'
import { Route as InvitationTokenRouteImport } from './routes/invitation/$token'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as ProfileUserIdIndexRouteImport } from './routes/profile/$userId/index'
import { Route as DashboardTreesIndexRouteImport } from './routes/dashboard/trees/index'
import { Route as DashboardTreesNewRouteImport } from './routes/dashboard/trees/new'
import { Route as DashboardTreesTreeIdRouteImport } from './routes/dashboard/trees/$treeId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiV1TreesIndexRouteImport } from './routes/api/v1/trees/index'
import { Route as ApiV1FamilyMembersIndexRouteImport } from './routes/api/v1/family-members/index'
import { Route as ApiV1TreesIdRouteImport } from './routes/api/v1/trees/$id'
import { Route as ApiV1GenealogyServicesRouteImport } from './routes/api/v1/genealogy/services'
import { Route as ApiV1FamilyMembersIdRouteImport } from './routes/api/v1/family-members/$id'
import { Route as DashboardTreesCompareTreeId1TreeId2RouteImport } from './routes/dashboard/trees/compare.$treeId1.$treeId2'
import { Route as ApiV1TreesIdRelationshipsRouteImport } from './routes/api/v1/trees/$id.relationships'
import { Route as ApiV1TreesIdMembersRouteImport } from './routes/api/v1/trees/$id.members'
import { Route as ApiV1TreesIdMarriagesRouteImport } from './routes/api/v1/trees/$id.marriages'
import { Route as ApiV1TreesIdImportRouteImport } from './routes/api/v1/trees/$id.import'
import { Route as ApiV1TreesIdExportRouteImport } from './routes/api/v1/trees/$id.export'
import { Route as ApiV1GenealogyImportTreeIdRouteImport } from './routes/api/v1/genealogy/import.$treeId'

const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TreeTreeIdRoute = TreeTreeIdRouteImport.update({
  id: '/tree/$treeId',
  path: '/tree/$treeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationTokenRoute = InvitationTokenRouteImport.update({
  id: '/invitation/$token',
  path: '/invitation/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const ProfileUserIdIndexRoute = ProfileUserIdIndexRouteImport.update({
  id: '/profile/$userId/',
  path: '/profile/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTreesIndexRoute = DashboardTreesIndexRouteImport.update({
  id: '/trees/',
  path: '/trees/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTreesNewRoute = DashboardTreesNewRouteImport.update({
  id: '/trees/new',
  path: '/trees/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTreesTreeIdRoute = DashboardTreesTreeIdRouteImport.update({
  id: '/trees/$treeId',
  path: '/trees/$treeId',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TreesIndexRoute = ApiV1TreesIndexRouteImport.update({
  id: '/api/v1/trees/',
  path: '/api/v1/trees/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FamilyMembersIndexRoute = ApiV1FamilyMembersIndexRouteImport.update({
  id: '/api/v1/family-members/',
  path: '/api/v1/family-members/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1TreesIdRoute = ApiV1TreesIdRouteImport.update({
  id: '/api/v1/trees/$id',
  path: '/api/v1/trees/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1GenealogyServicesRoute = ApiV1GenealogyServicesRouteImport.update({
  id: '/api/v1/genealogy/services',
  path: '/api/v1/genealogy/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV1FamilyMembersIdRoute = ApiV1FamilyMembersIdRouteImport.update({
  id: '/api/v1/family-members/$id',
  path: '/api/v1/family-members/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTreesCompareTreeId1TreeId2Route =
  DashboardTreesCompareTreeId1TreeId2RouteImport.update({
    id: '/trees/compare/$treeId1/$treeId2',
    path: '/trees/compare/$treeId1/$treeId2',
    getParentRoute: () => DashboardRoute,
  } as any)
const ApiV1TreesIdRelationshipsRoute =
  ApiV1TreesIdRelationshipsRouteImport.update({
    id: '/relationships',
    path: '/relationships',
    getParentRoute: () => ApiV1TreesIdRoute,
  } as any)
const ApiV1TreesIdMembersRoute = ApiV1TreesIdMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => ApiV1TreesIdRoute,
} as any)
const ApiV1TreesIdMarriagesRoute = ApiV1TreesIdMarriagesRouteImport.update({
  id: '/marriages',
  path: '/marriages',
  getParentRoute: () => ApiV1TreesIdRoute,
} as any)
const ApiV1TreesIdImportRoute = ApiV1TreesIdImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => ApiV1TreesIdRoute,
} as any)
const ApiV1TreesIdExportRoute = ApiV1TreesIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ApiV1TreesIdRoute,
} as any)
const ApiV1GenealogyImportTreeIdRoute =
  ApiV1GenealogyImportTreeIdRouteImport.update({
    id: '/api/v1/genealogy/import/$treeId',
    path: '/api/v1/genealogy/import/$treeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tree/$treeId': typeof TreeTreeIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/trees/$treeId': typeof DashboardTreesTreeIdRoute
  '/dashboard/trees/new': typeof DashboardTreesNewRoute
  '/dashboard/trees': typeof DashboardTreesIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/api/v1/family-members/$id': typeof ApiV1FamilyMembersIdRoute
  '/api/v1/genealogy/services': typeof ApiV1GenealogyServicesRoute
  '/api/v1/trees/$id': typeof ApiV1TreesIdRouteWithChildren
  '/api/v1/family-members': typeof ApiV1FamilyMembersIndexRoute
  '/api/v1/trees': typeof ApiV1TreesIndexRoute
  '/api/v1/genealogy/import/$treeId': typeof ApiV1GenealogyImportTreeIdRoute
  '/api/v1/trees/$id/export': typeof ApiV1TreesIdExportRoute
  '/api/v1/trees/$id/import': typeof ApiV1TreesIdImportRoute
  '/api/v1/trees/$id/marriages': typeof ApiV1TreesIdMarriagesRoute
  '/api/v1/trees/$id/members': typeof ApiV1TreesIdMembersRoute
  '/api/v1/trees/$id/relationships': typeof ApiV1TreesIdRelationshipsRoute
  '/dashboard/trees/compare/$treeId1/$treeId2': typeof DashboardTreesCompareTreeId1TreeId2Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tree/$treeId': typeof TreeTreeIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/trees/$treeId': typeof DashboardTreesTreeIdRoute
  '/dashboard/trees/new': typeof DashboardTreesNewRoute
  '/dashboard/trees': typeof DashboardTreesIndexRoute
  '/profile/$userId': typeof ProfileUserIdIndexRoute
  '/api/v1/family-members/$id': typeof ApiV1FamilyMembersIdRoute
  '/api/v1/genealogy/services': typeof ApiV1GenealogyServicesRoute
  '/api/v1/trees/$id': typeof ApiV1TreesIdRouteWithChildren
  '/api/v1/family-members': typeof ApiV1FamilyMembersIndexRoute
  '/api/v1/trees': typeof ApiV1TreesIndexRoute
  '/api/v1/genealogy/import/$treeId': typeof ApiV1GenealogyImportTreeIdRoute
  '/api/v1/trees/$id/export': typeof ApiV1TreesIdExportRoute
  '/api/v1/trees/$id/import': typeof ApiV1TreesIdImportRoute
  '/api/v1/trees/$id/marriages': typeof ApiV1TreesIdMarriagesRoute
  '/api/v1/trees/$id/members': typeof ApiV1TreesIdMembersRoute
  '/api/v1/trees/$id/relationships': typeof ApiV1TreesIdRelationshipsRoute
  '/dashboard/trees/compare/$treeId1/$treeId2': typeof DashboardTreesCompareTreeId1TreeId2Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/unauthenticated': typeof UnauthenticatedRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/invitation/$token': typeof InvitationTokenRoute
  '/sitemap/xml': typeof SitemapXmlRoute
  '/tree/$treeId': typeof TreeTreeIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/trees/$treeId': typeof DashboardTreesTreeIdRoute
  '/dashboard/trees/new': typeof DashboardTreesNewRoute
  '/dashboard/trees/': typeof DashboardTreesIndexRoute
  '/profile/$userId/': typeof ProfileUserIdIndexRoute
  '/api/v1/family-members/$id': typeof ApiV1FamilyMembersIdRoute
  '/api/v1/genealogy/services': typeof ApiV1GenealogyServicesRoute
  '/api/v1/trees/$id': typeof ApiV1TreesIdRouteWithChildren
  '/api/v1/family-members/': typeof ApiV1FamilyMembersIndexRoute
  '/api/v1/trees/': typeof ApiV1TreesIndexRoute
  '/api/v1/genealogy/import/$treeId': typeof ApiV1GenealogyImportTreeIdRoute
  '/api/v1/trees/$id/export': typeof ApiV1TreesIdExportRoute
  '/api/v1/trees/$id/import': typeof ApiV1TreesIdImportRoute
  '/api/v1/trees/$id/marriages': typeof ApiV1TreesIdMarriagesRoute
  '/api/v1/trees/$id/members': typeof ApiV1TreesIdMembersRoute
  '/api/v1/trees/$id/relationships': typeof ApiV1TreesIdRelationshipsRoute
  '/dashboard/trees/compare/$treeId1/$treeId2': typeof DashboardTreesCompareTreeId1TreeId2Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/invitation/$token'
    | '/sitemap/xml'
    | '/tree/$treeId'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/trees/$treeId'
    | '/dashboard/trees/new'
    | '/dashboard/trees'
    | '/profile/$userId'
    | '/api/v1/family-members/$id'
    | '/api/v1/genealogy/services'
    | '/api/v1/trees/$id'
    | '/api/v1/family-members'
    | '/api/v1/trees'
    | '/api/v1/genealogy/import/$treeId'
    | '/api/v1/trees/$id/export'
    | '/api/v1/trees/$id/import'
    | '/api/v1/trees/$id/marriages'
    | '/api/v1/trees/$id/members'
    | '/api/v1/trees/$id/relationships'
    | '/dashboard/trees/compare/$treeId1/$treeId2'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/invitation/$token'
    | '/sitemap/xml'
    | '/tree/$treeId'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/trees/$treeId'
    | '/dashboard/trees/new'
    | '/dashboard/trees'
    | '/profile/$userId'
    | '/api/v1/family-members/$id'
    | '/api/v1/genealogy/services'
    | '/api/v1/trees/$id'
    | '/api/v1/family-members'
    | '/api/v1/trees'
    | '/api/v1/genealogy/import/$treeId'
    | '/api/v1/trees/$id/export'
    | '/api/v1/trees/$id/import'
    | '/api/v1/trees/$id/marriages'
    | '/api/v1/trees/$id/members'
    | '/api/v1/trees/$id/relationships'
    | '/dashboard/trees/compare/$treeId1/$treeId2'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/sign-in'
    | '/sign-up'
    | '/unauthenticated'
    | '/dashboard/analytics'
    | '/dashboard/settings'
    | '/invitation/$token'
    | '/sitemap/xml'
    | '/tree/$treeId'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/trees/$treeId'
    | '/dashboard/trees/new'
    | '/dashboard/trees/'
    | '/profile/$userId/'
    | '/api/v1/family-members/$id'
    | '/api/v1/genealogy/services'
    | '/api/v1/trees/$id'
    | '/api/v1/family-members/'
    | '/api/v1/trees/'
    | '/api/v1/genealogy/import/$treeId'
    | '/api/v1/trees/$id/export'
    | '/api/v1/trees/$id/import'
    | '/api/v1/trees/$id/marriages'
    | '/api/v1/trees/$id/members'
    | '/api/v1/trees/$id/relationships'
    | '/dashboard/trees/compare/$treeId1/$treeId2'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  InvitationTokenRoute: typeof InvitationTokenRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
  TreeTreeIdRoute: typeof TreeTreeIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ProfileUserIdIndexRoute: typeof ProfileUserIdIndexRoute
  ApiV1FamilyMembersIdRoute: typeof ApiV1FamilyMembersIdRoute
  ApiV1GenealogyServicesRoute: typeof ApiV1GenealogyServicesRoute
  ApiV1TreesIdRoute: typeof ApiV1TreesIdRouteWithChildren
  ApiV1FamilyMembersIndexRoute: typeof ApiV1FamilyMembersIndexRoute
  ApiV1TreesIndexRoute: typeof ApiV1TreesIndexRoute
  ApiV1GenealogyImportTreeIdRoute: typeof ApiV1GenealogyImportTreeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/tree/$treeId': {
      id: '/tree/$treeId'
      path: '/tree/$treeId'
      fullPath: '/tree/$treeId'
      preLoaderRoute: typeof TreeTreeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$token': {
      id: '/invitation/$token'
      path: '/invitation/$token'
      fullPath: '/invitation/$token'
      preLoaderRoute: typeof InvitationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/profile/$userId/': {
      id: '/profile/$userId/'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trees/': {
      id: '/dashboard/trees/'
      path: '/trees'
      fullPath: '/dashboard/trees'
      preLoaderRoute: typeof DashboardTreesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trees/new': {
      id: '/dashboard/trees/new'
      path: '/trees/new'
      fullPath: '/dashboard/trees/new'
      preLoaderRoute: typeof DashboardTreesNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/trees/$treeId': {
      id: '/dashboard/trees/$treeId'
      path: '/trees/$treeId'
      fullPath: '/dashboard/trees/$treeId'
      preLoaderRoute: typeof DashboardTreesTreeIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/trees/': {
      id: '/api/v1/trees/'
      path: '/api/v1/trees'
      fullPath: '/api/v1/trees'
      preLoaderRoute: typeof ApiV1TreesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/family-members/': {
      id: '/api/v1/family-members/'
      path: '/api/v1/family-members'
      fullPath: '/api/v1/family-members'
      preLoaderRoute: typeof ApiV1FamilyMembersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/trees/$id': {
      id: '/api/v1/trees/$id'
      path: '/api/v1/trees/$id'
      fullPath: '/api/v1/trees/$id'
      preLoaderRoute: typeof ApiV1TreesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/genealogy/services': {
      id: '/api/v1/genealogy/services'
      path: '/api/v1/genealogy/services'
      fullPath: '/api/v1/genealogy/services'
      preLoaderRoute: typeof ApiV1GenealogyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v1/family-members/$id': {
      id: '/api/v1/family-members/$id'
      path: '/api/v1/family-members/$id'
      fullPath: '/api/v1/family-members/$id'
      preLoaderRoute: typeof ApiV1FamilyMembersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/trees/compare/$treeId1/$treeId2': {
      id: '/dashboard/trees/compare/$treeId1/$treeId2'
      path: '/trees/compare/$treeId1/$treeId2'
      fullPath: '/dashboard/trees/compare/$treeId1/$treeId2'
      preLoaderRoute: typeof DashboardTreesCompareTreeId1TreeId2RouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/v1/trees/$id/relationships': {
      id: '/api/v1/trees/$id/relationships'
      path: '/relationships'
      fullPath: '/api/v1/trees/$id/relationships'
      preLoaderRoute: typeof ApiV1TreesIdRelationshipsRouteImport
      parentRoute: typeof ApiV1TreesIdRoute
    }
    '/api/v1/trees/$id/members': {
      id: '/api/v1/trees/$id/members'
      path: '/members'
      fullPath: '/api/v1/trees/$id/members'
      preLoaderRoute: typeof ApiV1TreesIdMembersRouteImport
      parentRoute: typeof ApiV1TreesIdRoute
    }
    '/api/v1/trees/$id/marriages': {
      id: '/api/v1/trees/$id/marriages'
      path: '/marriages'
      fullPath: '/api/v1/trees/$id/marriages'
      preLoaderRoute: typeof ApiV1TreesIdMarriagesRouteImport
      parentRoute: typeof ApiV1TreesIdRoute
    }
    '/api/v1/trees/$id/import': {
      id: '/api/v1/trees/$id/import'
      path: '/import'
      fullPath: '/api/v1/trees/$id/import'
      preLoaderRoute: typeof ApiV1TreesIdImportRouteImport
      parentRoute: typeof ApiV1TreesIdRoute
    }
    '/api/v1/trees/$id/export': {
      id: '/api/v1/trees/$id/export'
      path: '/export'
      fullPath: '/api/v1/trees/$id/export'
      preLoaderRoute: typeof ApiV1TreesIdExportRouteImport
      parentRoute: typeof ApiV1TreesIdRoute
    }
    '/api/v1/genealogy/import/$treeId': {
      id: '/api/v1/genealogy/import/$treeId'
      path: '/api/v1/genealogy/import/$treeId'
      fullPath: '/api/v1/genealogy/import/$treeId'
      preLoaderRoute: typeof ApiV1GenealogyImportTreeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTreesTreeIdRoute: typeof DashboardTreesTreeIdRoute
  DashboardTreesNewRoute: typeof DashboardTreesNewRoute
  DashboardTreesIndexRoute: typeof DashboardTreesIndexRoute
  DashboardTreesCompareTreeId1TreeId2Route: typeof DashboardTreesCompareTreeId1TreeId2Route
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTreesTreeIdRoute: DashboardTreesTreeIdRoute,
  DashboardTreesNewRoute: DashboardTreesNewRoute,
  DashboardTreesIndexRoute: DashboardTreesIndexRoute,
  DashboardTreesCompareTreeId1TreeId2Route:
    DashboardTreesCompareTreeId1TreeId2Route,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ApiV1TreesIdRouteChildren {
  ApiV1TreesIdExportRoute: typeof ApiV1TreesIdExportRoute
  ApiV1TreesIdImportRoute: typeof ApiV1TreesIdImportRoute
  ApiV1TreesIdMarriagesRoute: typeof ApiV1TreesIdMarriagesRoute
  ApiV1TreesIdMembersRoute: typeof ApiV1TreesIdMembersRoute
  ApiV1TreesIdRelationshipsRoute: typeof ApiV1TreesIdRelationshipsRoute
}

const ApiV1TreesIdRouteChildren: ApiV1TreesIdRouteChildren = {
  ApiV1TreesIdExportRoute: ApiV1TreesIdExportRoute,
  ApiV1TreesIdImportRoute: ApiV1TreesIdImportRoute,
  ApiV1TreesIdMarriagesRoute: ApiV1TreesIdMarriagesRoute,
  ApiV1TreesIdMembersRoute: ApiV1TreesIdMembersRoute,
  ApiV1TreesIdRelationshipsRoute: ApiV1TreesIdRelationshipsRoute,
}

const ApiV1TreesIdRouteWithChildren = ApiV1TreesIdRoute._addFileChildren(
  ApiV1TreesIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  UnauthenticatedRoute: UnauthenticatedRoute,
  InvitationTokenRoute: InvitationTokenRoute,
  SitemapXmlRoute: SitemapXmlRoute,
  TreeTreeIdRoute: TreeTreeIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ProfileUserIdIndexRoute: ProfileUserIdIndexRoute,
  ApiV1FamilyMembersIdRoute: ApiV1FamilyMembersIdRoute,
  ApiV1GenealogyServicesRoute: ApiV1GenealogyServicesRoute,
  ApiV1TreesIdRoute: ApiV1TreesIdRouteWithChildren,
  ApiV1FamilyMembersIndexRoute: ApiV1FamilyMembersIndexRoute,
  ApiV1TreesIndexRoute: ApiV1TreesIndexRoute,
  ApiV1GenealogyImportTreeIdRoute: ApiV1GenealogyImportTreeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
